language: node_js
node_js:
- '10'
script:
- npm run travis
notifications:
  slack:
    secure: CDiXaDmWzsA2IpKZiST744uZooaoTuJ+qTMWElSWsHIp6cA/mbOLcZGsmhemmKaYvKl7ASF8doJrCaBinmy59Unzs0Er/Kfp1gwlQ4wpbOk3Bj072bgM3r8ipIunnEa0S6ynGK6n2OtUZOlnmUsP1dha9ndRVsT+vK4W9xqzsl0grRXcvv+56vkzvcPGq7rATMnbIpT4DvbzgX0NoAyZZMz6/R1CPnGVirp/7dHB6+OYkt6wooM0yCJS32G1JsjoZMwHSqs697pVOsOziO6LZ9NlBRp5Fv0SsIFQAroX6zqOkWjtjR8sPs8MDqw8K2pM7Wi4NKgV1qUTqi1a9ScfgRZ2cg9o2hKsPHBSpYq1v4ijlNm7O4gAs0t0XupJtrUS9gi1cAnHKT0/JJDLXRZOmAYIeSH76WnefAEpcXGKXKWqOQVlG4/cPbD9Xi3WswWVUoxrFCWM+ORGdfM/qMbUtBWfD1HCM13Sqv/DDX5F2gFGQZda1WjWZQ11HEnZWFhGvT7kDYbPc816XMP26gpq3xxsi9vtfmo09RvFRk2mTwlXAK8ppS40GeAlNOolxWjPGrWZBzwIBVUmRiyKZf4KgIkBD3z9woDQnoFr+FWwe1Yi0uqqhov1iI8iu/xhjdEP8PDyfy1FuoF4mlE0xqBAFqGx55SWFKxlMaBixRqoYf0=
deploy:
  provider: releases
  api_key:
    secure: 2lOmN1Y0nMcLx9y6rtL2YbpM+yXNpgJHQ4w40HMu5dcVOIT5nCjQZ+brTXNwjUvHASWyMNO8mz8/gltVb2uhDNceHtgoqSilCCIQA40wFUydh7djtK9wk/lyuka9LseFOvahMwZWyLsibVN0MqZBb0dJG+xCd3uBz2BwQuP3280Rq1KguoGqCjAozEAeejz2qkz8pLeVlaXGoyfdg2IgSQ9NzJOj0lgGL00zTlUWAdGh5WWpAhOk200qMxvA71HfMBzlamiX/cFcv02TBZfOt5yTgyOapERvJafAyRisBTcU5UqO6rqII6vHPmUPz6It7QF6XmE0iX+zRR7wumsKpaIh3+ee7YwLozdLLUHy0dBkn5PUQBpBn/TtlPwf2q5ibUsECc8zs6axyApULSodSPmgS+c+7pGJrIvFmYDm0JxntMwb1Dhx9NGuAeIHvrloqW2qcKvS29FRBrB5xcagdlz5gPT6OTgle6CCuhvNf/1fvczA1RRtolMDNeFy6cIjKf6RfWgiChyC50oqLOfF4QrmENxei+GmdGCD73jlJKF34yn9dBjgVVYvpoubdrya/j82ec41JrjKlpzL1CeYBHlqxDJMM3rthzb/JLHqWMgbASHGDZIv7nZpdEMJQTR4LkSvOhvMk8VhvjRXmadpxgUBu7T1yhWFsIKtX4idFsU=
  skip_cleanup: true
  file:
   - "dist/pagexray.js"
   - "dist/pagexray.min.js"
  on:
    tags: true
    node: '10'
    repo: sitespeedio/pagexray
